# Generated by Django 4.1.7 on 2023-06-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(blank=True, max_length=15)),
                ('player2', models.CharField(blank=True, max_length=15)),
                ('number_cards', models.IntegerField(choices=[(4, '4 cards'), (8, '8 cards'), (16, '16 cards'), (32, '32 cards')])),
                ('playboard', models.JSONField(blank=True, null=True)),
                ('moves', models.IntegerField(default=0)),
                ('winner', models.CharField(max_length=15)),
                ('scoreplayer1', models.IntegerField(default=0)),
                ('scoreplayer2', models.IntegerField(default=0)),
            ],
        ),
    ]
