# Generated by Django 4.1.2 on 2023-03-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player1", models.TextField(max_length=20)),
                ("player2", models.TextField(max_length=20)),
                ("number_cards", models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
    ]
