# Generated by Django 4.1.2 on 2023-03-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gra", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player1", models.TextField(max_length=20)),
                ("player2", models.TextField(max_length=20)),
                (
                    "number_cards",
                    models.DecimalField(decimal_places=0, default=10, max_digits=20),
                ),
            ],
        ),
        migrations.DeleteModel(name="Gra",),
    ]
