# Generated by Django 4.1.7 on 2023-04-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gra", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newgame",
            name="playboard",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newgame",
            name="number_cards",
            field=models.IntegerField(
                choices=[(4, "4cards"), (8, "8cards"), (16, "16cards"), (32, "32cards")]
            ),
        ),
    ]
