# Generated by Django 4.1.7 on 2023-03-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gra", "0002_newgame_delete_gra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newgame", name="player1", field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="newgame", name="player2", field=models.CharField(max_length=15),
        ),
    ]
