# Generated by Django 4.1.2 on 2023-05-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gra", "0003_newgame_pairs_total_alter_newgame_number_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="newgame", name="moves", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="newgame",
            name="pairs_total",
            field=models.IntegerField(null=True),
        ),
    ]
