# Generated by Django 4.1.7 on 2023-06-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0005_remove_newgame_pairs_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='scoreplayer1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='scoreplayer2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='winner',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
