# Generated by Django 4.1.2 on 2023-06-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gra", "0005_alter_newgame_id"),
        ("gra", "0007_alter_newgame_scoreplayer1_and_more"),
    ]

    operations = []
