# Generated by Django 4.1.2 on 2023-06-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gra", "0008_merge_20230619_0745"),
    ]

    operations = [
        migrations.AddField(
            model_name="newgame",
            name="current_playboard",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newgame",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
